# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.0.0
  flutter-orb: circleci/flutter@1.0.1
  ruby: circleci/ruby@1.6.0
  macos: circleci/macos@2.1.0

jobs:
  integration_test_android:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 2.10.3
      - android/create-avd:
          avd-name: flutter
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: flutter
          post-emulator-launch-assemble-command: 'flutter build apk --debug'
          restore-gradle-cache-find-args: ./android -name 'build.gradle'
      - android/run-tests:
          test-command: flutter test integration_test
      - store_artifacts:
          path: ozzie

  integration_test_ios:
    macos:
      xcode: 13.3.0
    resource_class: medium
    steps:
      - checkout
      - macos/preboot-simulator:
          device: iPhone 13
          version: "15.4"
      - flutter-orb/install_sdk_and_pub:
          flutter_version: 2.10.3
      - flutter-orb/install_ios_pod
      - run:
          name: Integration Test
          command: flutter test integration_test
      - store_artifacts:
          path: ozzie

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test_android_and_ios:
    jobs:
      - integration_test_android
      - integration_test_ios