version: 2.1

orbs:
  android: circleci/android@2.0.0
  flutter-orb: circleci/flutter@1.0.1
  # Refer to this link to setup Slack channels: https://github.com/CircleCI-Public/slack-orb/wiki/Setup
  # Setup slack app also:  https://github.com/CircleCI-Public/slack-orb/issues/207#issuecomment-731219733
  slack: circleci/slack@4.9.3
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build_and_test:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    working_directory: ~/project
    steps:
      - checkout
      # Note that sonar scan is triggered ONLY if automatic analysis is turned OFF
      - sonarcloud/scan
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 2.10.3
      - run:
          name: flutter clean
          command: flutter clean
      - run:
          name: flutter build apk
          command: flutter -v build apk --debug
      - store_artifacts:
          path: ~/project/build/app/outputs/flutter-apk
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job ${CIRCLE_JOB} ${CCI_STATUS}.",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main