# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0

jobs:
  distribute:
    macos:
      xcode: 12.5.1
    steps:
      - flutter/install_sdk_and_pub
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run:
          command: flutter --version
          working_directory: ios
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  distribute: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - distribute
