version: 2.1

orbs:
  android: circleci/android@2.0.0
  flutter-orb: circleci/flutter@1.0.1

jobs:
  integration_test_android:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 2.10.3
      - run:
          name: flutter clean
          command: flutter clean
      - run:
          name: flutter build apk
          command: flutter -v build apk

workflows:
  test_android_and_ios:
    jobs:
      - integration_test_android